<script lang="ts">
	import { onMount } from 'svelte';
	import { createHighlighter, type Highlighter } from 'shiki';
	import type { Highlight } from '$lib/model/types.js';

	let {
		code,
		language,
		highlight
	}: {
		code: string;
		language: string;
		highlight?: Highlight | null;
	} = $props();

	let highlighter = $state<Highlighter | null>(null);
	let html = $state<string>('');
	let error = $state<string | null>(null);

	onMount(async () => {
		try {
			highlighter = await createHighlighter({
				themes: ['github-dark'],
				langs: ['typescript', 'javascript', 'python', 'html', 'css']
			});
		} catch (e) {
			console.error('Failed to initialize Shiki:', e);
			error = 'Failed to load syntax highlighter';
		}
	});

	$effect(() => {
		if (highlighter && code && language) {
			try {
				html = highlighter.codeToHtml(code, {
					lang: language,
					theme: 'github-dark',
					transformers: [
						{
							line(node, line) {
								if (highlight && line >= highlight.startLine && line <= highlight.endLine) {
									this.addClassToHast(node, 'bg-yellow-500/20');
									this.addClassToHast(node, 'w-full');
									this.addClassToHast(node, 'inline-block');
								}
							}
						}
					]
				});
			} catch (e) {
				console.error('Failed to highlight code:', e);
				// Fallback to plain text if highlighting fails (e.g., unsupported language)
				html = `<pre><code>${escapeHtml(code)}</code></pre>`;
			}
		}
	});

	function escapeHtml(unsafe: string) {
		return unsafe
			.replace(/&/g, '&amp;')
			.replace(/</g, '&lt;')
			.replace(/>/g, '&gt;')
			.replace(/"/g, '&quot;')
			.replace(/'/g, '&#039;');
	}
</script>

<div class="code-block-container overflow-hidden rounded-lg bg-[#24292e] text-sm">
	{#if error}
		<div class="bg-red-900/20 p-4 text-red-400">{error}</div>
		<pre class="overflow-x-auto p-4 text-gray-300"><code>{code}</code></pre>
	{:else if html}
		<!-- eslint-disable-next-line svelte/no-at-html-tags -->
		<div class="shiki-wrapper overflow-x-auto p-4">{@html html}</div>
	{:else}
		<div class="animate-pulse p-4 text-gray-400">Loading highlighter...</div>
		<pre class="overflow-x-auto p-4 text-gray-300 opacity-50"><code>{code}</code></pre>
	{/if}
</div>

<style>
	/* Ensure the pre tag generated by shiki has no margin and fills the container */
	:global(.shiki-wrapper pre) {
		margin: 0;
		background-color: transparent !important;
	}

	/* Ensure code block takes full width so line highlights span the whole container */
	:global(.shiki-wrapper code) {
		display: block;
		min-width: fit-content;
	}
</style>
